import 'package:gelir_gider/models/transaction_model.dart';

final List<TransactionModel> fakeTransactions = [
  TransactionModel(
    id: "1",
    title: "Elektrik",
    category: "Fatura",
    amount: 750,
    date: DateTime(2026, 1, 10),
    type: TransactionType.expense,
  ),
  TransactionModel(
    id: "2",
    title: "Su",
    category: "Fatura",
    amount: 1200,
    date: DateTime(2026, 2, 10),
    type: TransactionType.expense,
  ),
  TransactionModel(
    id: "3",
    title: "Ali",
    category: "Maaş",
    amount: 50000,
    date: DateTime(2026, 1, 10),
    type: TransactionType.income,
  ),
  TransactionModel(
    id: "4",
    title: "Araba Camı Yapıldı",
    category: "Araba",
    amount: 500,
    date: DateTime(2026, 7, 10),
    type: TransactionType.expense,
  ),
  TransactionModel(
    id: "5",
    title: "Mahkeme Harcı",
    category: "Adli",
    amount: 500,
    date: DateTime(2026, 5, 10),
    type: TransactionType.expense,
  ),
  TransactionModel(
    id: "6",
    title: "Dogalgaz",
    category: "Fatura",
    amount: 3500,
    date: DateTime(2026, 1, 2),
    type: TransactionType.expense,
  ),
  TransactionModel(
    id: "7",
    title: "İnternet",
    category: "Fatura",
    amount: 1000,
    date: DateTime(2026, 1, 27),
    type: TransactionType.expense,
  ),
  TransactionModel(
    id: "8",
    title: "Telefon",
    category: "Fatura",
    amount: 900,
    date: DateTime(2026, 1, 9),
    type: TransactionType.expense,
  ),
  TransactionModel(
    id: "9",
    title: "D-Smart",
    category: "Fatura",
    amount: 200,
    date: DateTime(2026, 1, 11),
    type: TransactionType.expense,
  ),
];
