import 'package:gelir_gider/models/transaction_model.dart';

final List<TransactionModel> fakeTransactions = [
  TransactionModel(
    id: "1",
    comment: "Elektrik",
    category: "Faturalar",
    amount: 750,
    date: DateTime(2026, 1, 10),
    type: TransactionType.expense,
    paymentType: PaymentType.bankCard,
  ),
  TransactionModel(
    id: "2",
    comment: "Su",
    category: "Faturalar",
    amount: 1200,
    date: DateTime(2026, 2, 10),
    type: TransactionType.expense,
    paymentType: PaymentType.bankCard,
  ),
  TransactionModel(
    id: "3",
    comment: "Ali",
    category: "Maaş",
    amount: 50000,
    date: DateTime(2026, 1, 10),
    type: TransactionType.income,
    paymentType: PaymentType.bankCard,
  ),
  TransactionModel(
    id: "4",
    comment: "Araba Camı Yapıldı",
    category: "Diğer",
    amount: 500,
    date: DateTime(2026, 7, 10),
    type: TransactionType.expense,
    paymentType: PaymentType.bankCard,
  ),
  TransactionModel(
    id: "5",
    comment: "Mahkeme Harcı",
    category: "Diğer",
    amount: 500,
    date: DateTime(2026, 5, 10),
    type: TransactionType.expense,
  ),
  TransactionModel(
    id: "6",
    comment: "Dogalgaz",
    category: "Faturalar",
    amount: 3500,
    date: DateTime(2026, 1, 2),
    type: TransactionType.expense,
    paymentType: PaymentType.bankCard,
  ),
  TransactionModel(
    id: "7",
    comment: "İnternet",
    category: "Faturalar",
    amount: 1000,
    date: DateTime(2026, 1, 27),
    type: TransactionType.expense,
    paymentType: PaymentType.cash,
  ),
  TransactionModel(
    id: "8",
    comment: "Telefon",
    category: "Faturalar",
    amount: 900,
    date: DateTime(2026, 1, 9),
    type: TransactionType.expense,
    paymentType: PaymentType.bankCard,
  ),
  TransactionModel(
    id: "9",
    comment: "D-Smart",
    category: "Faturalar",
    amount: 200,
    date: DateTime(2026, 1, 11),
    type: TransactionType.expense,
    paymentType: PaymentType.bankCard,
  ),
];
